#!/bin/bash



RELEASES="2.6.34
2.6.35
2.6.36
2.6.37
2.6.38
2.6.39
3.0
3.1
3.2
3.3"

echo "Release, Num of Referential Global Defects, Poss Cause, Poss Fix, Undecided"

for release in $RELEASES
do

python ../../../Code/Scripts/GitScripts/extract-matched-stats.py --release $release --matches ./$release/defectCPP_Pairs_$release.dict --missing ./$release/missingFeatures_$release.dict

done

